---
title: "GBD Plots"
output: html_document
date: "2023-04-16"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F)
```

```{r}
pacman::p_load(tidyverse,
               tidylog,
               readxl,
               ggrepel,
               broom)

library(readr)
lifetableallBR_panel <- read_csv("~/Downloads/lifetableallBR_panel.csv")

dt <- lifetableallBR_panel

dt |> count(location_name)

dt_filter <- dt |> filter(location_name %in% c("Bahia", "Santa Catarina"),
                          age_group_name %in% c("<1 year",
                                                "40 to 44",
                                                "70 to 74")) |>
  mutate(split_year=if_else(year_id < 1981, "0", "1"))
                          


dt_filter |> ggplot(aes(year_id, val, color=location_name, shape=age_group_name))+
  geom_point(size=0.8)+
  geom_smooth(alpha=0.4, size=0.5)+
  geom_vline(aes(xintercept=1978),linetype="dotted")+
  theme_minimal()+
  scale_x_continuous(breaks = seq(1950,2020,10))+
  scale_y_continuous(limits = c(0,80),
                     breaks = seq(0,80,10))+
  labs(x="",
       y="Additional life expactancy",
       color="Age group")+
  theme(legend.position = "bottom")+
  annotate("text", x=1960, y=70, label="difSCxBA -4.71\n[-5.56 to -3.85]", size=6)

### modelling ###
pacman::p_load(forestmangr, modelbased)
lm1 <- lm(val ~ year_id*age_group_name*location_name*split_year, data = dt_filter)
lm_con <-  estimate_contrasts(lm1, contrast = c("location_name", "age_group_name=c('<1 year')","split_year"))
lm1
lm_con

lm_res <- pacf(residuals(lm1))

### diff ###

dt_filter_diff <- dt_filter|>  
  group_by(location_name,
           age_group_name) |> 
  mutate(diff_life = val- lag(val))

dt_filter_diff

### piecewise linear regression ###

pacman::p_load(segmented)

dt_piece <- dt_filter |> filter(location_name=="Bahia", age_group_name=="<1 year")
piece_dt <- lm(val ~ year_id, dt_piece)
piece_dt

dt_seg <- segmented(piece_dt)
summary(dt_seg)
plot(dt_seg)
```

